### ISSUE TITLE
Some very confusing parts about your paper.

### ISSUE THREAD

**Issue by Magicboomliu** [aim-uofa/FreeCompose#2]
Thank you for your outstanding work. 

However, when I am reading your paper, I get confused about some of the descriptions and the formula, just list as follows:

(1) The equation at page 5 about the diffusion model here, `z` should be `z(t-1)`:
<img width="320" alt="image" src="https://github.com/user-attachments/assets/e6ee90db-6160-4133-9395-48aeff5afec0">

(2)In the object removal part: 
<img width="629" alt="image" src="https://github.com/user-attachments/assets/b2c1bf7c-16bb-4ff5-b194-15ac813ff3a5">
and   
<img width="833" alt="image" src="https://github.com/user-attachments/assets/a92535bc-64bc-4242-96ca-fa7e37f5db32">
where is the `I(t)` from? I guess it should be the masked `K` and `V` result initial from the `I(s)` through the diffusion models with the `P(t)`, because at this stage , the `P(o)` and `P(t)` are just placeholders, so the only thing that DDS can work should be the attention masks. But how to get the initial `I(t)` is not clear, is it  the foreground image as you state at the beginning of your section?

(3) In the Image Harmonization Part: 
<img width="933" alt="image" src="https://github.com/user-attachments/assets/5a6df570-6845-4d1a-9e32-73e443dd03fc">
The same, how can we get the initial `I(t)`? And what is I(t)?

**Comment by Aziily** [comment]
Thank you for pointing out these issues. `I(t)` is initialized from input image `I(s)` and then utilized as an optimizable tensor, the same with Delta Denoising Score. I probably forgot to mention this part in the preliminary.

**Comment by Aziily** [comment]
If there are some other issues, please let me know.
